name: Deploying Terraform Infrastructure for Webapp

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform
        uses: hashicorp/setup-terraform@v3

      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color

