name: Deploying Terraform Infrastructure for Webapp

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform
        uses: hashicorp/setup-terraform@v3

      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color

